### ISSUE TITLE
`pinch_zoom_image` does not specify a Swift version 

### ISSUE THREAD

**Issue by raegartargarian** [YoussefKababe/pinch_zoom_image#14]
pinch_zoom_image: "^0.2.5"

console output

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing path_provider (0.0.1)

    -> Installing pinch_zoom_image (0.0.1)

    -> Installing shared_preferences (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `pinch_zoom_image` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute
    set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:115:in
    `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/bin/pod:22:in `<main>'

**Comment by eriko13** [comment]
I have the same problem.

**Comment by furkankurt** [comment]
I created new repo. Owner of this project don't accept pull requests. You can use mine.
https://pub.dartlang.org/packages/pinch_zoom_image_last
If there is an issue, you can open an issue of my github repo.
