### ISSUE TITLE
Kotlin Gradle plugin version build error

### ISSUE THREAD

**Issue by agnoam** [YoussefKababe/pinch_zoom_image#21]
Hey,
I'm trying your plugin, but when I compiled my app. 
Build crashed with this exception: 
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':pinch_zoom_image' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
```

**Comment by lotustha** [comment]
Same here

**Comment by lotustha** [comment]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':pinch_zoom_image' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by praharshbhatt** [comment]
Same issue here

**Comment by A-Rhman** [comment]
same here :/

**Comment by perseval** [comment]
any solution ?

**Comment by hemant6488** [comment]
I just published this plugin from my account after upgrading the kotlin version to 1.3.10.
Include: 
**pinch_zoom_image_updated: ^0.2.6**
https://pub.dev/packages/pinch_zoom_image_updated

**Comment by perseval** [comment]
> I just published this plugin from my account after upgrading the kotlin version to 1.3.10.
> Include:
> **pinch_zoom_image_updated: ^0.2.6**
> https://pub.dev/packages/pinch_zoom_image_updated

`
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
`

**Comment by macmatrix** [comment]
@hemant6488 thanks for providing the update. Android works great but the plugin does not work for iOS. Here is the error I get if I try to run in iOS

> [!] No podspec found for `pinch_zoom_image_updated` in `.symlinks/plugins/pinch_zoom_image_updated/ios`

any solution?

**Comment by hgouveia** [comment]
same issue
