### ISSUE TITLE
Issue running on iOS simulator,

### ISSUE THREAD

**Issue by vishna** [YoussefKababe/pinch_zoom_image#4]
pinch_zoom_image: "^0.2.5"

console output
```
    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing path_provider (0.0.1)

    -> Installing pinch_zoom_image (0.0.1)

    -> Installing shared_preferences (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `pinch_zoom_image` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute
    set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:115:in
    `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/bin/pod:22:in `<main>'
```

**Comment by shamnex** [comment]
Getting the same error. Did you manage to fix it?

**Comment by vishna** [comment]
nope, removed the package for now to get my app working - the fix should just be matter of forking and trying out a SWIFT_VERSION that works - if I have time, I'll make a PR

**Comment by vishna** [comment]
anyway, today I've put this (latest master)

```
  pinch_zoom_image:
    git:
      url: git@github.com:YoussefKababe/pinch_zoom_image.git
      ref: a73858972cb5383ae862bbc5ce066bde99e986b8
```

and it just worked ¯\\\_(ツ)_/¯

**Comment by furkankurt** [comment]
I created new repo. Owner of this project don't accept pull requests. You can use mine.
https://pub.dartlang.org/packages/pinch_zoom_image_last
If there is an issue, you can open an issue of my github repo.
